services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_DB=petclinic
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U petclinic -d petclinic'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "12456:5432"
  app:
    build:
      context: .
      target: prod
    environment:
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_URL=jdbc:postgresql://db:5432/petclinic
      - SPRING_PROFILES_ACTIVE=postgres
volumes:
  postgres-volume:      
